version: '3'
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 
      DB_NAME: OrgXplor
      DB_PORT: 5432
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=OrgXplor
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-schema:/docker-entrypoint-initdb.d/schema.sql
